import {KpiCard} from "@/components/KpiCard";import {compactMoney} from "@/lib/format";import {getDashboardMetrics,getPipeline} from "@/lib/data/crm";
export default async function Dashboard(){
 const [metrics,pipeline]=await Promise.all([getDashboardMetrics(),getPipeline()]);
 const stageCounts=pipeline.stages.map(s=>({...s,count:pipeline.cards.filter(c=>c.stage_id===s.id).length}));const max=Math.max(...stageCounts.map(s=>s.count),1);
 return <><div className="page-head"><div><h1>Chào buổi sáng 👋</h1><p>Những việc đội sale cần xử lý hôm nay.</p></div><a className="primary-btn" href="/leads">+ Thêm lead</a></div>
 <section className="kpi-grid"><KpiCard label="Lead mới" value={String(metrics.newLeads)} hint="+12% so với tuần trước"/><KpiCard label="Đã hẹn / Check-in" value={String(metrics.appointments)} hint="6 lịch trong hôm nay"/><KpiCard label="Đã đăng ký" value={String(metrics.enrolled)} hint="Theo dõi tỷ lệ chốt"/><KpiCard label="Doanh thu đã thu" value={compactMoney(metrics.collectedRevenue)} hint="Doanh thu đã ghi nhận"/></section>
 <section className="two-col"><div className="surface panel"><div className="panel-head"><div><h2>Funnel tuyển sinh</h2><p>Theo pipeline hiện tại</p></div></div><div className="funnel-list">{stageCounts.map(s=><div className="funnel-row" key={s.id}><span>{s.name}</span><div className="funnel-bar"><i style={{width:`${Math.max(8,s.count/max*100)}%`,background:s.color}}/></div><b>{s.count}</b></div>)}</div></div>
 <div className="surface panel"><div className="panel-head"><div><h2>Cần chú ý</h2><p>Ưu tiên xử lý trước</p></div></div><div className="notice-list"><div className="notice danger"><b>{metrics.overdueTasks} việc quá hạn</b><span>Cần EC hoặc HoEC xử lý ngay.</span></div><div className="notice warning"><b>{metrics.openAlerts} việc cần quản lý</b><span>Đang chờ HoEC / SM can thiệp.</span></div><div className="notice info"><b>Lead đa cơ sở</b><span>Mỗi cơ sở có pipeline và EC phụ trách riêng.</span></div></div></div></section></>
}
